openapi: 3.0.0
info:
  title: Flight API
  description: |
    The best flight checking API you've ever seen.
    If it's not the best API you've ever seen you're a liar.
  version: 0.0.1
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
paths:
  /routes/{Route_UUID}:
    post:
      summary:  Update Route
      parameters:
        - name: Route_UUID
          in: path
          required: true
          description: Identifier of the route the customer is taking.
          schema:
            type : string
          example: "577B4ADB-FCB6-43A5-845B-918A952CB9B4"
      requestBody:
        required: true
        content:
          application/json:
            example: [{ "route_UUID": "577B4ADB-FCB6-43A5-845B-918A952CB9B4",
                "origin": "1 Infinfite Loop Cupertino, CA 95014 United States",
                "destination": "80 Nassau St Unit 4C New York, NY 10038 United States",
                "start_time": "2017-07-21T17:32:28Z",
                "end_time": "2017-07-21T17:32:28Z",
                "seat_capacity": 7,
                "price_per_Seat": 120
              }]
            schema:
              type: array
              items:
                type: object
                properties:
                  product_id:
                    type: string
                    example: 14DAFFD0-7E0F-4B28-B7EF-19C6EF45704A
                  quantity:
                    type: integer
                    minimum: 1
                    maximum: 12
                    example: 2
                  customizations:
                    type: object
                    example: {
                      color: 'blue',
                      sizeObj: {
                        type: 'W',
                        value: 10
                      }
                    }              
      responses:
        '200':    # status code
          description: A JSON body of flight objects
          content:
            application/json:
              schema: 
                type: string
                flights: 
                  type: string
                  example: {"route_UUID": "577B4ADB-FCB6-43A5-845B-918A952CB9B4",
                "origin": "1 Infinfite Loop Cupertino, CA 95014 United States",
                "destination": "80 Nassau St Unit 4C New York, NY 10038 United States",
                "start_time": "2017-07-21T17:32:28Z",
                "end_time": "2017-07-21T17:32:28Z",
                "seat_capacity": 7,
                "price_per_Seat": 120}
        '500': 
            description: |
              Returns detailed error explanation that routes was unable
              to fulfil the request
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorObject'
        '400':
          description: |
            Returns detailed error explanation in case client submitted invalid
            data to routes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'         
  /flights/{origin, destination, start_time, end_time}:
      get:
        summary: Get Flights
        description: |
          Get the status of flights provided by origin, destination, and optionally start time, and end time
        parameters:
          - name: origin
            description: Where the customer is coming from.
            in: path
            required: true
            schema:
              type: string
            example: "1 Infinfite Loop Cupertino, CA 95014 United States"
          - name: destination
            description: Where the customer is going.
            in: path
            required: true
            schema:
              type: string
            example: "80 Nassau St Unit 4C New York, NY 10038 United States"
          - name: start_time
            description: Time the customer is going to leave.
            in: path
            required: false
            schema:
              type: date-time
            example: "2017-07-21T17:32:28Z"
          - name: end_time
            description: Time the customer is wants to arrive.
            in: path
            required: false
            schema:
              type: date-time
            example: "2017-07-21T17:32:28Z"
        responses:
          '200':    # status code
            description: A JSON body of flight objects
            content:
              application/json:
                schema: 
                  type: string
                  flights: 
                    type: string
                    example: {
                  "flight_ID": "14DAFFD0-6KEO-4B28-B7EF-19C6AZ45704A",
                  "origin": "1 Infinfite Loop Cupertino, CA 95014 United States",
                  "destination": "80 Nassau St Unit 4C New York, NY 10038 United States",
                  "start_time": "2017-07-21T17:32:28Z",
                  "end_time": "2017-07-21T17:32:28Z",
                  "seat_capacity": 7,
                  "price_per_Seat": 120}
          '500': 
              description: |
                Returns detailed error explanation that flights was unable
                to fulfil the request
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ErrorObject'
          '400':
            description: |
              Returns detailed error explanation in case client submitted invalid
              data to flights
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorObject'         
components:
  schemas:
    ErrorObject:
      type: object
      properties:
        errorId:
          type: integer
        description:
          type: string
        details:
          type: string
      example:
        errorId: 2345
        description: "Could not connect to database"
        details: "Please contact sysadmin"