openapi: 3.0.0
info:
  title: Flight API
  description: |
    The best flight checking API you've ever seen.
    If it's not the best API you've ever seen you're a liar... or you might be right honestly.
  version: 0.0.1
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
paths:
  /routes:
    post:
      summary:  Update Route
      parameters:
        - name: route_UUID
          in: path
          required: true
          description: Identifier of the route the customer is taking.
          schema:
            type : string
          example: "577B4ADB-FCB6-43A5-845B-918A952CB9B4"
      requestBody:
        required: true
        content:
          application/json:            
            schema:
              type: array
              items:
                type: object
                properties:
                  origin:
                    type: string
                    example: "1 Infinfite Loop Cupertino, CA 95014 United States"
                  destination:
                    type: string
                    example: "80 Nassau St Unit 4C New York, NY 10038 United States"
                  start_time:
                      type: string
                      example: "2017-07-21T17:32:28Z"
                  end_time:
                      type: string
                      example: "2017-07-21T17:32:28Z"
                  seat_capacity:
                      type: integer
                      example: 7
                  price_per_Seat:
                      type: number
                      example: 120.00
                  data: 
                    type: object
                    example: { 
                  "origin": "1 Infinfite Loop Cupertino, CA 95014 United States",
                  "destination": "80 Nassau St Unit 4C New York, NY 10038 United States",
                  "start_time": "2017-07-21T17:32:28Z",
                  "end_time": "2017-07-21T17:32:28Z",
                  "seat_capacity": 7,
                  "price_per_Seat": 120.00
                  }            
      responses:
        '200':    # status code
          description:  A JSON body of flight objects
          content:
            application/json:            
              schema:
                type: array
                items:
                  type: object
                  properties:
                  
                    data:
                      type: object 
                      example: { 
                  "origin": "1 Infinfite Loop Cupertino, CA 95014 United States",
                  "destination": "80 Nassau St Unit 4C New York, NY 10038 United States",
                  "start_time": "2017-07-21T17:32:28Z",
                  "end_time": "2017-07-21T17:32:28Z",
                  "seat_capacity": 7,
                  "price_per_Seat": 120.00
                  }
        '500': 
            description: |
              Returns detailed error explanation that routes was unable
              to fulfil the request
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorObject'
        '400':
          description: |
            Returns detailed error explanation in case client submitted invalid
            data to routes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'         
  /flights:
      get:
        summary: Get Flights
        description: |
          Get the status of flights provided by origin, destination, and optionally start time, and end time
        parameters:
          - in: query
            name: origin
            description: Where the customer is coming from.
            schema:
              type: string
             # enum: [user, poweruser, admin]
            example: "1 Infinfite Loop Cupertino, CA 95014 United States"
            required: true
          - name: destination
            description: Where the customer is going.
            in: query
            required: true
            schema:
              type: string
            example: "80 Nassau St Unit 4C New York, NY 10038 United States"
          - name: start_time
            description: Time the customer is going to leave.
            in: query
            required: false
            schema:
              type: string
            example: "2017-07-21T17:32:28Z"
          - name: end_time
            description: Time the customer is wants to arrive.
            in: query
            required: false
            schema:
              type: string
            example: "2017-07-21T17:32:28Z"
        responses:
          '200':    # status code
            description: A JSON body of flight objects
            content:
              application/json:            
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      flight_ID: 
                        type: string
                        example: "14DAFFD0-6KEO-4B28-B7EF-19C6AZ45704A"
                      origin:
                        type: string
                        example: "1 Infinfite Loop Cupertino, CA 95014 United States"
                      destination: 
                        type: string
                        example: "80 Nassau St Unit 4C New York, NY 10038 United States"
                      start_time:
                        type: string
                        example: "2017-07-21T17:32:28Z"
                      end_time:
                        type: string 
                        example:  "2017-07-21T17:32:28Z"
                      seat_capacity: 
                        type: integer
                        example: 7
                      price_per_Seat: 
                        type: number
                        example: 120.00
                      data: 
                        type: object
                        example: { 
                      "origin": "1 Infinfite Loop Cupertino, CA 95014 United States",
                      "destination": "80 Nassau St Unit 4C New York, NY 10038 United States",
                      "start_time": "2017-07-21T17:32:28Z",
                      "end_time": "2017-07-21T17:32:28Z",
                      "seat_capacity": 7,
                      "price_per_Seat": 120.00
                      }
          '500': 
              description: |
                Returns detailed error explanation that flights was unable
                to fulfil the request
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ErrorObject'
          '400':
            description: |
              Returns detailed error explanation in case client submitted invalid
              data to flights
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorObject'         
components:
  schemas:
    ErrorObject:
      type: object
      properties:
        errorId:
          type: integer
        description:
          type: string
        details:
          type: string
      example:
        errorId: 2345
        description: "Could not connect to database"
        details: "Please contact sysadmin"